Adding new intents + training examples
RasaHQ/NLU-training-data pull request #56
Opened 2020-10-25 21:24 UTC by luiseloi

Adding new intents, namely: online_banking, retirement_plan, change_pin, interest_rate. Also contributing with some extra examples on transfer_money. I'd suggest the duplicate intents to be merged together.

2020-10-25 21:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RasaHQ/NLU-training-data?pullRequest=56) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RasaHQ/NLU-training-data?pullRequest=56) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RasaHQ/NLU-training-data?pullRequest=56) it.</sub>

2020-10-26 07:00 UTC, sara-tagger commented
Thanks for submitting a pull request 🚀 @samsucik will take a look at it as soon as possible ✨

2020-10-26 08:45 UTC, samsucik commented
Hi @luiseloi, thanks a lot for the contribution! Before we go ahead and merge it, could you add the new intents to the README as well? Additionally, I agree that `transfer_money` shouldn't be twice in the NLU file. Do you want to go ahead and merge the two groups of `transfer_money` examples together? :-)

2020-10-26 21:43 UTC, luiseloi commented
Hi, sure! Still starting to contribute, so I didn't want to mess up with the work already done there. I also merged the currency duplicates to keep it clean.

2020-10-27 08:45 UTC, samsucik requested changes
Looks good, thanks! I've left two minor comments :-)

2020-10-27 08:45 UTC, samsucik commented on banking/nlu.md
> +# intent:change_pin <!--The user wants to change his/her pin code-->
```suggestion
# intent:change_pin <!--The user wants to change their pin code-->
```

2020-10-27 08:45 UTC, samsucik commented on banking/nlu.md
> +# intent:lost_card <!--The user lost his/her card-->
```suggestion
# intent:lost_card <!--The user lost their card-->
```

2020-10-27 08:48 UTC, luiseloi commented
Cool, thanks :)

2021-01-15 12:25 UTC, EmmaWightman approved these changes

2021-01-15 12:27 UTC, EmmaWightman approved these changes

2021-01-15 12:27 UTC, merged